spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
    timeout: 1000ms
    jedis:
      pool:
        min-idle: 500
        max-wait: 1000ms
        max-active: 8
        max-idle: 8